//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HACK_portfolio
{
    public partial class _Default
    {
        /// <summary>
        /// home control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel home;

        /// <summary>
        /// ProjectsRepeater control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater ProjectsRepeater;

        /// <summary>
        /// modalImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image modalImage;

        /// <summary>
        /// backToTop control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button backToTop;

        /// <summary>
        /// contactEmailLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink contactEmailLink;

        /// <summary>
        /// contactAddress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label contactAddress;
    }
}
