//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HACK_portfolio
{
    public partial class Login
    {
        protected global::System.Web.UI.WebControls.Label loginStatus;

        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        protected global::System.Web.UI.WebControls.Button btnSignIn;
    }
}
