//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HACK_portfolio
{
    public partial class SiteMaster
    {
        protected global::System.Web.UI.WebControls.HyperLink navLogin;
    }
}
