//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HACK_portfolio.admin
{
    public partial class dashboard
    {
        /// <summary>
        /// lblAdminName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAdminName;

        /// <summary>
        /// lblTotalProjects control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalProjects;

        /// <summary>
        /// lblTotalUsers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalUsers;

        /// <summary>
        /// lblActiveProjects control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblActiveProjects;

        /// <summary>
        /// lblPendingRequests control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPendingRequests;
    }
}
