//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HACK_portfolio.admin
{
    public partial class edit_project
    {
        /// <summary>
        /// lblPageTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPageTitle;

        /// <summary>
        /// pnlSuccessMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSuccessMessage;

        /// <summary>
        /// txtProjectName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtProjectName;

        /// <summary>
        /// ddlCategory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;

        /// <summary>
        /// ddlStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;

        /// <summary>
        /// txtShortDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtShortDescription;

        /// <summary>
        /// txtDetailedDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDetailedDescription;

        /// <summary>
        /// txtThumbnailUrl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtThumbnailUrl;

        /// <summary>
        /// txtCoverImageUrl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCoverImageUrl;

        /// <summary>
        /// txtDemoUrl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDemoUrl;

        /// <summary>
        /// txtGitHubUrl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtGitHubUrl;

        /// <summary>
        /// txtVideoUrl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtVideoUrl;

        /// <summary>
        /// txtTechnologies control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTechnologies;

        /// <summary>
        /// txtTags control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTags;

        /// <summary>
        /// chkIsFeatured control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkIsFeatured;

        /// <summary>
        /// chkIsPublished control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkIsPublished;

        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;

        /// <summary>
        /// btnCancel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancel;
    }
}
