//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HACK_portfolio.admin
{
    public partial class edit_user
    {
        /// <summary>
        /// lblPageTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPageTitle;

        /// <summary>
        /// pnlSuccessMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSuccessMessage;

        /// <summary>
        /// txtUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtUsername;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// ddlRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlRole;

        /// <summary>
        /// chkIsActive control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkIsActive;

        /// <summary>
        /// chkIsEmailVerified control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkIsEmailVerified;

        /// <summary>
        /// txtFirstName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFirstName;

        /// <summary>
        /// txtLastName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLastName;

        /// <summary>
        /// txtPhoneNumber control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPhoneNumber;

        /// <summary>
        /// txtStudentID control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtStudentID;

        /// <summary>
        /// txtDepartment control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDepartment;

        /// <summary>
        /// txtYearOfStudy control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtYearOfStudy;

        /// <summary>
        /// txtBio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBio;

        /// <summary>
        /// txtSkills control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSkills;

        /// <summary>
        /// txtProfileImageUrl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtProfileImageUrl;

        /// <summary>
        /// txtLinkedInUrl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLinkedInUrl;

        /// <summary>
        /// txtGitHubUrl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtGitHubUrl;

        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;

        /// <summary>
        /// btnCancel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancel;
    }
}
