//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HACK_portfolio.admin
{
    public partial class settings
    {
        /// <summary>
        /// txtMinPasswordLength control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMinPasswordLength;

        /// <summary>
        /// chkRequireUppercase control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkRequireUppercase;

        /// <summary>
        /// chkRequireNumbers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkRequireNumbers;

        /// <summary>
        /// chkRequireSpecialChars control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkRequireSpecialChars;

        /// <summary>
        /// txtSessionTimeout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSessionTimeout;

        /// <summary>
        /// btnSaveSettings control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSaveSettings;

        /// <summary>
        /// btnResetSettings control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnResetSettings;

        /// <summary>
        /// pnlSuccessMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSuccessMessage;
    }
}
